/**
 * System Status & Action Enums
 * Perfectly aligned with the Nimufly platform domain model
 */

export const APPLICATION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  APPLICATION_RECEIVED: 'APPLICATION_RECEIVED',
  DOCUMENTS_UNDER_REVIEW: 'DOCUMENTS_UNDER_REVIEW',
  PROCESSING: 'PROCESSING',
  ADDITIONAL_INFORMATION_REQUIRED: 'ADDITIONAL_INFORMATION_REQUIRED',
  APPROVED: 'APPROVED',
  VISA_ISSUED: 'VISA_ISSUED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
});

export const REQUIRED_ACTION = Object.freeze({
  NONE: 'NONE',
  UPDATE_PHOTO: 'UPDATE_PHOTO',
  UPLOAD_DOCUMENT: 'UPLOAD_DOCUMENT',
  VIEW_VISA: 'VIEW_VISA',
  VIEW_APPLICATION: 'VIEW_APPLICATION'
});

export const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
});

export const PAYMENT_PROVIDER = Object.freeze({
  MOCK: 'MOCK',
  RAZORPAY: 'RAZORPAY',
  STRIPE: 'STRIPE'
});

export const DOCUMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  NEEDS_REUPLOAD: 'NEEDS_REUPLOAD'
});

export const ENTITY_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
});

export const AUDIT_ACTIONS = Object.freeze({
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  STATUS_CHANGE: 'STATUS_CHANGE',
  DOCUMENT_VERIFY: 'DOCUMENT_VERIFY',
  DOCUMENT_REJECT: 'DOCUMENT_REJECT',
  PRICE_UPDATE: 'PRICE_UPDATE',
  ADMIN_NOTE_ADDED: 'ADMIN_NOTE_ADDED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  LOGIN: 'LOGIN'
});

export const AUDIT_ENTITIES = Object.freeze({
  APPLICATION: 'APPLICATION',
  VISA: 'VISA',
  COUNTRY: 'COUNTRY',
  DOCUMENT: 'DOCUMENT',
  PAYMENT: 'PAYMENT',
  USER: 'USER',
  DOCUMENTATION_SERVICE: 'DOCUMENTATION_SERVICE',
  DUMMY_TICKET_SERVICE: 'DUMMY_TICKET_SERVICE'
});
